#include "../shared.h"

LibData box2d_data = {
    .name = BOX2D_LIB,
    .src_files = (const char *[34]){
        "external/box2d/src/aabb.c",
        "external/box2d/src/arena_allocator.c",
        "external/box2d/src/array.c",
        "external/box2d/src/bitset.c",
        "external/box2d/src/body.c",
        "external/box2d/src/broad_phase.c",
        "external/box2d/src/constraint_graph.c",
        "external/box2d/src/contact.c",
        "external/box2d/src/contact_solver.c",
        "external/box2d/src/core.c",
        "external/box2d/src/distance.c",
        "external/box2d/src/distance_joint.c",
        "external/box2d/src/dynamic_tree.c",
        "external/box2d/src/geometry.c",
        "external/box2d/src/hull.c",
        "external/box2d/src/id_pool.c",
        "external/box2d/src/island.c",
        "external/box2d/src/joint.c",
        "external/box2d/src/manifold.c",
        "external/box2d/src/math_functions.c",
        "external/box2d/src/motor_joint.c",
        "external/box2d/src/mover.c",
        "external/box2d/src/physics_world.c",
        "external/box2d/src/prismatic_joint.c",
        "external/box2d/src/revolute_joint.c",
        "external/box2d/src/sensor.c",
        "external/box2d/src/shape.c",
        "external/box2d/src/solver.c",
        "external/box2d/src/solver_set.c",
        "external/box2d/src/table.c",
        "external/box2d/src/timer.c",
        "external/box2d/src/types.c",
        "external/box2d/src/weld_joint.c",
        "external/box2d/src/wheel_joint.c",
    },
    .src_files_count = 34,

    .header_files = (const char *[6]){
        "external/box2d/include/box2d/base.h",
        "external/box2d/include/box2d/box2d.h",
        "external/box2d/include/box2d/collision.h",
        "external/box2d/include/box2d/id.h",
        "external/box2d/include/box2d/math_functions.h",
        "external/box2d/include/box2d/types.h",
    },
    .header_files_count = 6,

    .include_dirs = (const char *[1]){"external/box2d/include"},
    .include_dirs_count = 1,

    .custom_flags = (const char *[2]){"-O3", "-DNDEBUG"},
    .custom_flags_count = 2,
};
